sudo: false
cache: bundler

language: node_js

node_js:
  - 'iojs'
  - "0.12"
  - "0.10"

script: grunt test

before_install:
  - npm install -g grunt-cli bower
  - gem install bundler
  - bundle install

before_script:
  - npm install
  - bower install
